language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.8"
os:
  - linux
before_install: #installing unreleased packages
    - pip install git+https://github.com/databio/henge.git
    - pip install git+https://github.com/databio/refget-py
install:
  - pip install .
  - pip install -r requirements/requirements-dev.txt
  - pip install -r requirements/requirements-test.txt
script: pytest --remote-data --cov=refgenconf
branches:
  only:
    - dev
    - master
